Fixed some error handling.

diff --git a/doasedit b/doasedit
--- a/doasedit
+++ b/doasedit
@@ -3,18 +3,28 @@
 # AUTHOR: koalagang (https://github.com/koalagang)
 # Dependencies: doas
 
+error () {
+    echo "$1" && exit 0
+}
+
 # catch arguments
-[ -f "$1" ] || no_file=1 && [ -n "$no_file" ] && echo 'doasedit: no file path provided' && exit 0
-[ -n "$2" ] && echo 'doasedit: expected only one argument' && exit 0
-[ "$(whoami)" = 'root' ] && echo 'doasedit: cannot be run as root' && exit 0
+[ -f "$1" ] || no_file=1
+[ -z "$1" ] && error 'doasedit: no file path provided'
+[ -n "$2" ] && error 'doasedit: expected only one argument'
+[ "$(whoami)" = 'root' ] && error 'doasedit: cannot be run as root'
+[ -w "$1" ] && error 'doasedit: editing files in a writeable directory is not permitted'
 
 # if the source file contains an extension then that will be used for the temporary file as well
 dot='.'
 test "${1#*$dot}" != "$1" && temp="$(mktemp --suffix=."${1#*.}")" || temp="$(mktemp)"
 
-cat "$1" > "$temp" && $EDITOR "$temp" || no_edit=1 && [ -n "$no_edit" ] && echo 'doasedit: failed to file' && exit 0 # copy the contents of the source file to the temporary file
+if [ -z "$no_file" ]; then
+    cat "$1" > "$temp" && $EDITOR "$temp" || error 'doasedit: failed to copy file'
+elif [ -n "$no_file" ]; then
+    $EDITOR "$temp" && doas chown -c root:root "$temp" >/dev/null && doas chmod 0444 "$temp"
+fi
 
-cmp "$1" "$temp" -s && echo "doasedit: '$1' unchanged" && exit 0 # if the file is unchanged then exit
+cmp "$1" "$temp" -s && echo "doasedit: $1 unchanged" && exit 0 # if the file is unchanged then exit
 
 # replace the source file with the temporary file (but retain the name of the source file)
 # repeats if it fails (i.e. the user typed the password in wrong)
